#! /usr/bin/env python3
import sys
from decrypt import Decrypt

if len(sys.argv) < 2 or len(sys.argv) > 2:
        sys.exit(1)

if __name__ == "__main__":
    decrypt = Decrypt(sys.argv[1])
    trans = decrypt.process()
    decrypt.print_stream(trans)

    accounts = decrypt.get_accounts(trans)
    account = next((k for k, v in accounts.items() if v == 1), None)

    stream = decrypt.get_stream()
    start = stream.index(account) - 2
    end = start + 5
    replay = stream[start:end]

    output_data = "".join(stream + replay)
    with open("task2.out", "wb") as out_file:
      out_file.write(bytes.fromhex(output_data))
