#! /usr/bin/env python3
import sys
from decrypt import Decrypt

if len(sys.argv) < 2 or len(sys.argv) > 2 :
        sys.exit(1)

if __name__ == "__main__":
    decrypt = Decrypt(sys.argv[1])
    trans = decrypt.process()
    decrypt.print_stream(trans)

    accounts = decrypt.get_accounts(trans)
    next = next((k for k, v in accounts.items() if v == 1), None)

    stream = decrypt.get_stream()
    target = stream.index(next) - 2

    time = stream.index(trans["transfer"]) + 4

    replace = [
        trans["transfer"],
        stream[target + 1],
        stream[target + 2],
        stream[target + 3],
        stream[time],
    ]

    stream[target:target + len(replace) - 1] = replace

    with open("task4.out", "wb") as out_file:
        out_file.write(bytes.fromhex("".join(stream)))
